# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cilium
  - ./cert-manager
  - ./democratic-csi
  - ./tailscale
  - ./vault
  - ./external-secrets
  - ./cnpg
  - ./nfd
  - ./intel-device-plugins
