apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "https://vault.vault.svc.cluster.local:8200"
      path: "kv/homelab"
      version: "v2"
      caProvider:
        type: Secret
        name: vault-server-tls
        key: ca.crt
        namespace: vault
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "external-secrets"
